### ISSUE TITLE
Not installable via `npm`

### ISSUE THREAD

**Issue by briandipalma** [systemjs/plugin-css#1]
I tried installing this via `npm` as GitHub repo dependency and it fails. I think it's down to the fact that the `package.json` file is not complete/standard. Is this repo meant to be an npm package?

**Comment by dchambers** [comment]
Hi @guybedford, was this closed because it was fixed or no longer relevant?

I was originally using [system-css](https://www.npmjs.com/package/system-css) (a thirdparty NPM package for this repo), but it's stuck on an earlier version, and I needed a fix in the `0.1.13` release, so changed my `package.json` to have an entry like this:

```json
"plugin-css": "systemjs/plugin-css#0.1.13"
```

but that caused a `No name provided in package.json` error when I subsequently ran `npm install`.

**Comment by marjan-georgiev** [comment]
@dchambers you should be able to install it with

```sh
jspm install github:systemjs/plugin-css@0.1.13
```

**Comment by dchambers** [comment]
Hi @marjan-georgiev, thanks for the suggestion, but this issue is about installing this plug-in via NPM rather than JSPM.
